[package]
name = "da-trie"
version = "0.1.0"
authors = ["Koichi Nakanishi <keizo042dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
